### PR TITLE
Cards documentation

### PR DESCRIPTION
**Pull request by aquadila**
Documentation for the Cards API endpoints.

### CODE REVIEW

**Comment by tjg37** [comment]
Feedback

- Add an explanation of the different card statuses to the card section.

**Comment by tjg37** [comment]
The only issue that I came across is that it looks like the responses for `GET /user/cards/`, `GET /user/cards/{id}/`, `POST /user/cards/`,  `POST /user/cards/{id}/set_primary/` and `POST /user/cards/{id}/verify/` (in the case where 3ds is not required) in the docs are missing the registration status in the response: `"registration_status": "registered",`. This is still included in the actual response, but as we discussed today shouldn't it be removed from the actual API response? If it's removed from the actual response then the docs are correct.

**Comment by aquadila** [comment]
Noted. Changes to the docs PR were not pushed in the `Cards` until recently, even though the amendments to the two PR's were done at the same time. Thanks for pointing it out though.

**Comment by aquadila** [comment]
Added `unverified` status to the available verification statuses in the docs.

**Pull request merged**
